# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function for calculating exponentially weighted moving average. Written in
#' C++.
#' @param x An atomic vector
#' @param lamb A double
#' @export
ewma <- function(x, lambda = 0.975) {
    .Call('powerfor_ewma', PACKAGE = 'powerfor', x, lambda)
}

